name = "ewsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "news_now"
database_id = "5813e619-8309-445d-bbc3-b09eb2f27122"
